import "./global.css";
import "@mantine/core/styles.css";
import "react-toastify/dist/ReactToastify.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import { ToastContainer } from "react-toastify";
import QueryProvider from "./queryProvider";

export const metadata = {
	title: "Selçuk Giray",
	description: "Generated by Selçuk Giray",
};

const theme = createTheme({
	defaultRadius: "md",
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<QueryProvider>
					<MantineProvider theme={theme}>
						<ToastContainer autoClose={500} />
						{children}
					</MantineProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
